### PR TITLE
Adding STP support

### PR DESCRIPTION
**Pull request by tpetriv**
This is patch for LACP support, made by PLvision company team.
Please review the changes, introduced by Our team. Any questions can be adressed to my mail.
Kind Regards
Taras

### CODE REVIEW

**Comment by pstavirs** [comment]
Thank you for your contribution. Can you please confirm that the feedback given in #143 has been addressed? I'm looking for point-wise confirmation of the feedback.

**Comment by tpetriv** [comment]
Hello. I can confirm that most of notes of #143 are considered in #169. Except :

* pdmlreader.cpp
#  - please maintain alphabetic order for
    - factory_.insert()

Do we need  to create new pull with fix it? Or we can do this in future when additions or changes in a patch are made?

**Comment by pstavirs** [comment]
Apologize for the delay. The STP protocol has been committed after minor cleanup and changes.

Thank you for your contribution to the project. I hope you will be able to help in case of any queries or reported bugs about the STP code.

**Comment by tpetriv** [comment]
Great!
We were glad to help to a common Good!
Sure We will cooperate in future.

Good luck!
Taras

**Pull request merged**
