### PR TITLE
make python-ostinato python3 compliant (work in progress)

### PR DESCRIPTION
**Pull request by little-dude**
I'm hitting several issues here:
- protobuf 2.6.1 seems not to work with python 3.5: https://github.com/google/protobuf/issues/1276
- protobuf 3.0.0.b2 fixes the previous issue, but the generated code has buggy import statements. I can fix them manually but I'll first wait for protobuf developers to comment on the issue: https://github.com/google/protobuf/issues/1491

### CODE REVIEW

**Comment by pstavirs** [comment]
Ostinato doesn't build with protobuf3 - https://github.com/pstavirs/ostinato/issues/167

Let's wait for Google to fix problem in 2.6.1

**Comment by little-dude** [comment]
Yeah I didn't even try it, since it's a different project. I have hope that protobuf-3.0.0 will be released soon with a fix for the issue I opened, though.

**Comment by little-dude** [comment]
so if this get merged, we can support python 3: https://github.com/google/protobuf/pull/1511

**Comment by pstavirs** [comment]
Stale PR, plus the Ostinato Python API is no longer part of this repo.

Closing.

**Pull request closed without merging**
