### PR TITLE
 lacp protocol patch. PLvision company 128

### PR DESCRIPTION
**Pull request by tpetriv**
Hello Srivats,
This is fix of issue 128, made by PLvision company team. 
Latest version was commited to branch, here is original repo 
https://code.google.com/r/developers-lacp-plvision/

Please review the changes, introduced by Our team. Any questions can be adressed to my mail. 
Kind Regards
Taras

### CODE REVIEW

**Comment by pstavirs** [comment]
My guess is you forked the github repo and patched in changes from the
googlecode repo, but the code has moved forward since the googlecode base
code you used to make the LACP changes. This is showing up as changes in
code unrelated to LACP.

Please fix this and resubmit. Also, please ensure/confirm that all feedback
comments given during the code review have been addressed.

On Mon, Oct 12, 2015 at 7:14 AM, tpetriv <notifications@github.com> wrote:

> Hello Srivats,
> This is fix of issue 128, made by PLvision company team.
> Latest version was commited to branch, here is original repo
> https://developers%40plvision.eu@code.google.com
> /r/developers-lacp-plvision/
>
> Please review the changes, introduced by Our team. Any questions can be
> adressed to my mail.
> Kind Regards
> Taras
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/pstavirs/ostinato/pull/163
> Commit Summary
>
>    - lacp protocol patch. PLvision company 128
>
> File Changes
>
>    - *T* .gitignore
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-0> (0)
>    - *A* .hgignore
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-1> (38)
>    - *T* .travis.yml
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-2> (0)
>    - *T* README.md
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-3> (0)
>    - *M* binding/core.py
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-4> (1)
>    - *T* client/icons/stream_duplicate.png
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-5> (0)
>    - *M* client/main.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-6> (15)
>    - *M* client/mainwindow.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-7> (32)
>    - *M* client/mainwindow.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-8> (7)
>    - *M* client/mainwindow.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-9> (27)
>    - *M* client/ostinato.pro
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-10> (14)
>    - *M* client/ostinato.qrc
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-11> (1)
>    - *M* client/port.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-12> (34)
>    - *M* client/port.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-13> (10)
>    - *M* client/portconfigdialog.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-14> (65)
>    - *M* client/portconfigdialog.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-15> (2)
>    - *M* client/portconfigdialog.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-16> (43)
>    - *M* client/portgroup.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-17> (88)
>    - *M* client/portgroup.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-18> (3)
>    - *M* client/portmodel.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-19> (10)
>    - *M* client/portstatsfilterdialog.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-20> (9)
>    - *M* client/portstatsfilterdialog.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-21> (3)
>    - *M* client/portstatsmodel.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-22> (19)
>    - *M* client/portstatsmodel.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-23> (13)
>    - *T* client/portstatsproxymodel.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-24> (0)
>    - *M* client/portstatswindow.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-25> (123)
>    - *M* client/portstatswindow.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-26> (15)
>    - *M* client/portswindow.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-27> (160)
>    - *M* client/portswindow.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-28> (12)
>    - *M* client/portswindow.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-29> (8)
>    - *M* client/preferences.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-30> (29)
>    - *M* client/preferences.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-31> (2)
>    - *M* client/settings.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-32> (2)
>    - *M* client/streamconfigdialog.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-33> (27)
>    - *M* client/streamconfigdialog.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-34> (16)
>    - *T* client/updater.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-35> (0)
>    - *T* client/updater.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-36> (0)
>    - *T* client/variablefieldswidget.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-37> (0)
>    - *T* client/variablefieldswidget.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-38> (0)
>    - *T* client/variablefieldswidget.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-39> (0)
>    - *M* common/abstractfileformat.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-40> (7)
>    - *M* common/abstractprotocol.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-41> (258)
>    - *M* common/abstractprotocol.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-42> (30)
>    - *M* common/arp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-43> (17)
>    - *M* common/arp.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-44> (1)
>    - *M* common/comboprotocol.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-45> (17)
>    - *M* common/dot3.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-46> (9)
>    - *M* common/dot3.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-47> (1)
>    - *M* common/fileformat.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-48> (2)
>    - *M* common/gmp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-49> (18)
>    - *M* common/gmp.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-50> (1)
>    - *M* common/icmp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-51> (2)
>    - *M* common/ip4.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-52> (33)
>    - *M* common/ip4.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-53> (1)
>    - *M* common/ip6.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-54> (48)
>    - *M* common/ip6.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-55> (1)
>    - *A* common/lacp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-56> (1252)
>    - *A* common/lacp.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-57> (137)
>    - *A* common/lacp.proto
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-58> (79)
>    - *A* common/lacp.ui
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-59> (2231)
>    - *A* common/lacpconfig.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-60> (498)
>    - *A* common/lacpconfig.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-61> (44)
>    - *A* common/lacppdml.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-62> (99)
>    - *A* common/lacppdml.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-63> (41)
>    - *M* common/mac.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-64> (11)
>    - *M* common/mac.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-65> (1)
>    - *M* common/ostproto.pro
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-66> (3)
>    - *M* common/ostprotogui.pro
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-67> (6)
>    - *M* common/payload.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-68> (9)
>    - *M* common/pdmlreader.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-69> (2)
>    - *M* common/protocol.proto
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-70> (37)
>    - *M* common/protocolmanager.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-71> (3)
>    - *M* common/protocolwidgetfactory.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-72> (4)
>    - *T* common/pythonfileformat.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-73> (0)
>    - *T* common/pythonfileformat.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-74> (0)
>    - *M* common/sample.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-75> (16)
>    - *M* common/sample.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-76> (1)
>    - *M* common/streambase.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-77> (4)
>    - *M* common/tcp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-78> (16)
>    - *M* common/tcp.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-79> (1)
>    - *M* common/udp.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-80> (22)
>    - *M* common/udp.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-81> (1)
>    - *M* common/userscript.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-82> (20)
>    - *M* common/userscript.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-83> (7)
>    - *M* protobuf.pri
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-84> (4)
>    - *M* rpc/pbqtio.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-85> (6)
>    - *M* rpc/pbrpcchannel.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-86> (127)
>    - *M* rpc/pbrpcchannel.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-87> (8)
>    - *M* rpc/pbrpccommon.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-88> (5)
>    - *M* rpc/pbrpccontroller.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-89> (8)
>    - *M* rpc/rpcconn.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-90> (43)
>    - *M* rpc/rpcconn.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-91> (8)
>    - *M* rpc/rpcserver.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-92> (3)
>    - *M* rpc/rpcserver.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-93> (6)
>    - *T* rpc/sharedprotobufmessage.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-94> (0)
>    - *M* server/abstractport.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-95> (12)
>    - *M* server/drone.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-96> (7)
>    - *M* server/drone.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-97> (4)
>    - *M* server/drone.pro
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-98> (5)
>    - *M* server/drone_main.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-99> (27)
>    - *M* server/linuxport.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-100> (107)
>    - *M* server/myservice.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-101> (12)
>    - *M* server/myservice.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-102> (8)
>    - *M* server/pcapport.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-103> (2)
>    - *M* server/portmanager.cpp
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-104> (56)
>    - *M* server/portmanager.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-105> (3)
>    - *T* server/settings.h
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-106> (0)
>    - *T* test/harness.py
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-107> (0)
>    - *T* test/vftest.py
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-108> (0)
>    - *M* version.pri
>    <https://github.com/pstavirs/ostinato/pull/163/files#diff-109> (4)
>
> Patch Links:
>
>    - https://github.com/pstavirs/ostinato/pull/163.patch
>    - https://github.com/pstavirs/ostinato/pull/163.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/163>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by tpetriv** [comment]
I have merged freshly forked code with patch from https://developers%40plvision.eu@code.google.com/r/developers-lacp-plvision/ . should not it be ok? Or the patch itself should be updated? Guys working on this code are way far on other projects so it would be good if We finalize this issue and integrate changes into main track.

**Comment by pstavirs** [comment]
You have not merged, you have blindly overwritten the files from the old
patch deleting all the code that was added in the master branch since the
code base that was originally used to add LACP.

Srivats

On Mon, Oct 19, 2015 at 4:55 AM, tpetriv <notifications@github.com> wrote:

> I have merged freshly forked code with patch from https://developers%
> 40plvision.eu@code.google.com/r/developers-lacp-plvision/ . should not it
> be ok? Or the patch itself should be updated? Guys working on this code are
> way far on other projects so it would be good if We finalize this issue and
> integrate changes into main track.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/163#issuecomment-149193108>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by tpetriv** [comment]
So the patch is out-dated, or it has been badly merged ? 
Thanks
Taras

**Comment by pstavirs** [comment]
Both

On Tue, Oct 20, 2015 at 1:58 AM, tpetriv <notifications@github.com> wrote:

> So the patch is out-dated, or it has been badly merged ?
> Thanks
> Taras
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/163#issuecomment-149483406>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by tpetriv** [comment]
Hello,

We still wish to merge existing patch, but We lack info on the fault itself
and it`s reproduction.
I suppose that this info was lost during move of Ostinato proj to git,
right?

Thanks
Taras

**Comment by pstavirs** [comment]
I'm sorry, I don't understand - what fault and reproduction are you talking
about?

No information was lost during transition from googlecode to github.

Srivats

On Mon, Nov 16, 2015 at 7:16 PM, tpetriv <notifications@github.com> wrote:

> Hello,
>
> We still wish to merge existing patch, but We lack info on the fault itself
> and it`s reproduction.
> I suppose that this info was lost during move of Ostinato proj to git,
> right?
>
> Thanks
> Taras
>
> On Tue, Oct 20, 2015 at 5:21 PM, Srivats P. <notifications@github.com>
> wrote:
>
> > Both
> >
> > On Tue, Oct 20, 2015 at 1:58 AM, tpetriv <notifications@github.com>
> wrote:
> >
> > > So the patch is out-dated, or it has been badly merged ?
> > > Thanks
> > > Taras
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pstavirs/ostinato/pull/163#issuecomment-149483406
> >.
> >
> > >
> >
> >
> >
> > --
> > http://ostinato.org/
> > @ostinato
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pstavirs/ostinato/pull/163#issuecomment-149582273>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/163#issuecomment-157030514>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by tpetriv** [comment]
Hello,

The matter is in bug 128, as far as I know it is connected to lacp.
PLvision guys were fixing it some 7 or 8 month ago.
Sorry for bothering, just want to close all left-overs.

Kind Regards
T

**Comment by pstavirs** [comment]
I would be happy to merge the LACP contribution once it is in a state where
it could be merged, which currently it is not.

It shouldn't take much to provide the right diff - anyone with experience
of version control can get it done. Also my comments in #128 also need to
be addressed. If you or someone else can get this done, I'll do a final
review and accept the pull request.




On Tue, Nov 17, 2015 at 3:34 PM, tpetriv <notifications@github.com> wrote:

> Hello,
>
> The matter is in bug 128, as far as I know it is connected to lacp.
> PLvision guys were fixing it some 7 or 8 month ago.
> Sorry for bothering, just want to close all left-overs.
>
> Kind Regards
> T
>
> On Mon, Nov 16, 2015 at 5:03 PM, Srivats P. <notifications@github.com>
>
> wrote:
>
> > I'm sorry, I don't understand - what fault and reproduction are you
> talking
> > about?
> >
> > No information was lost during transition from googlecode to github.
> >
> > Srivats
> >
> > On Mon, Nov 16, 2015 at 7:16 PM, tpetriv <notifications@github.com>
> wrote:
> >
> > > Hello,
> > >
> > > We still wish to merge existing patch, but We lack info on the fault
> > itself
> > > and it`s reproduction.
> > > I suppose that this info was lost during move of Ostinato proj to git,
> > > right?
> > >
> > > Thanks
> > > Taras
> > >
> > > On Tue, Oct 20, 2015 at 5:21 PM, Srivats P. <notifications@github.com>
> > > wrote:
> > >
> > > > Both
> > > >
> > > > On Tue, Oct 20, 2015 at 1:58 AM, tpetriv <notifications@github.com>
> > > wrote:
> > > >
> > > > > So the patch is out-dated, or it has been badly merged ?
> > > > > Thanks
> > > > > Taras
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/pstavirs/ostinato/pull/163#issuecomment-149483406
> > > >.
> > > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > http://ostinato.org/
> > > > @ostinato
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/pstavirs/ostinato/pull/163#issuecomment-149582273
> > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pstavirs/ostinato/pull/163#issuecomment-157030514
> >.
> >
> > >
> >
> >
> >
> > --
> > http://ostinato.org/
> > @ostinato
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pstavirs/ostinato/pull/163#issuecomment-157060306>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/163#issuecomment-157325599>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by pstavirs** [comment]
Stale PR. Closing.

**Pull request closed without merging**
