### PR TITLE
Add MPLS support

### PR DESCRIPTION
**Pull request by volchanetskiy**
First of all, thank you for this great piece of software.
I tried to add MPLS support to Ostinato. I'm not experienced, so I probably did some things wrong.
And here are the things I'm not sure about:
- I didn't know where to place MPLS in `protocol.proto`, `ostproto.pro` and `ostprotogui.pro` files
- MPLS is only available under Advanced "tab"
- It looks like EXP field has been renamed to "Traffic Class" but it's still called "EXP" in Wireshark and PDML. I used "exp" everywhere except for UI.
- There are two EtherType values for MPLS: `0x8847` and `0x8848` "for unicast and multicast connections respectively", but I set the first one as `protocolId`, one would have to set EtherType manually to use multicast

### CODE REVIEW

**Comment by pstavirs** [comment]
Thank you for your contribution!

I will review the changes shortly and get back to you.

On Sat, Oct 10, 2015 at 8:33 AM, volchanetskiy <notifications@github.com>
wrote:

> First of all, thank you for this great piece of software.
> I tried to add MPLS support to Ostinato. I'm not experienced, so I
> probably did some things wrong.
> And here are the things I'm not sure about:
>
>    - I didn't know where to place MPLS in protocol.proto, ostproto.pro
>    and ostprotogui.pro files
>    - MPLS is only available under Advanced "tab"
>    - It looks like EXP field has been renamed to "Traffic Class" but it's
>    still called "EXP" in Wireshark and PDML. I used "exp" everywhere except
>    for UI.
>    - There are two EtherType values for MPLS: 0x8847 and 0x8848 "for
>    unicast and multicast connections respectively", but I set the first one as
>    protocolId, one would have to set EtherType manually to use multicast
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/pstavirs/ostinato/pull/162
> Commit Summary
>
>    - Add MPLS support
>
> File Changes
>
>    - *A* common/mpls.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-0> (296)
>    - *A* common/mpls.h
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-1> (83)
>    - *A* common/mpls.proto
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-2> (37)
>    - *A* common/mpls.ui
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-3> (164)
>    - *A* common/mplsconfig.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-4> (85)
>    - *A* common/mplsconfig.h
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-5> (44)
>    - *A* common/mplspdml.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-6> (42)
>    - *A* common/mplspdml.h
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-7> (37)
>    - *M* common/ostproto.pro
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-8> (3)
>    - *M* common/ostprotogui.pro
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-9> (4)
>    - *M* common/pdmlreader.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-10> (2)
>    - *M* common/protocol.proto
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-11> (1)
>    - *M* common/protocolmanager.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-12> (3)
>    - *M* common/protocolwidgetfactory.cpp
>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-13> (4)
>
> Patch Links:
>
>    - https://github.com/pstavirs/ostinato/pull/162.patch
>    - https://github.com/pstavirs/ostinato/pull/162.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/162>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by pstavirs** [comment]
I took a quick look at the changes. I think we should implement a label
stack in the protocol instead of a single label. In fact, I now think that
the Vlan protocol should also have implemented multiple vlan tags and I
will most likely change this sometime in the future.

The bottom-of-stack should be set automatically and I don't see any use
case that will require a override of the flag. Even if there is a rare
case, it can be done using a hexdump protocol. If you think otherwise, let
me know and we can discuss. Otherwise if you agree, we can remove the
is_override_bos field

Some other points -
* Is the choice of having default label value as 0 a considered/explicit
reason?If so, could you please share? Note that I'm not saying 0 should not
be the default value - I'm just saying we should consider what default
value we want to use
* Remove empty constructors and destructors and other member functions
which are just calling the base class function
(e.g.protocolFrameVariableCount())

Answers to your queries -
* I didn't know where to place MPLS in protocol.proto, ostproto.pro and
ostprotogui.pro files
[srivats] Your current placements are perfect!

* MPLS is only available under Advanced "tab"
[srivats] It is ok for now, I will consider adding it to the Simple mode in
the GUI at a later date

* It looks like EXP field has been renamed to "Traffic Class" but it's
still called "EXP" in Wireshark and PDML. I used "exp" everywhere except
for UI.
[srivats] Ok

* There are two EtherType values for MPLS: 0x8847 and 0x8848 "for unicast
and multicast connections respectively", but I set the first one as
protocolId, one would have to set EtherType manually to use multicast
[srivats] RFC 5332 seems to have defined a different purpose for 0x8848 -
other than multicast, but I think what you've done is fine

Once you've made the above suggested changes, I'll take a more detailed
look at the changes.

Srivats

On Tue, Oct 13, 2015 at 6:15 AM, Srivats P <pstavirs@gmail.com> wrote:

> Thank you for your contribution!
>
> I will review the changes shortly and get back to you.
>
> On Sat, Oct 10, 2015 at 8:33 AM, volchanetskiy <notifications@github.com>
> wrote:
>
>> First of all, thank you for this great piece of software.
>> I tried to add MPLS support to Ostinato. I'm not experienced, so I
>> probably did some things wrong.
>> And here are the things I'm not sure about:
>>
>>    - I didn't know where to place MPLS in protocol.proto, ostproto.pro
>>    and ostprotogui.pro files
>>    - MPLS is only available under Advanced "tab"
>>    - It looks like EXP field has been renamed to "Traffic Class" but
>>    it's still called "EXP" in Wireshark and PDML. I used "exp" everywhere
>>    except for UI.
>>    - There are two EtherType values for MPLS: 0x8847 and 0x8848 "for
>>    unicast and multicast connections respectively", but I set the first one as
>>    protocolId, one would have to set EtherType manually to use multicast
>>
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/pstavirs/ostinato/pull/162
>> Commit Summary
>>
>>    - Add MPLS support
>>
>> File Changes
>>
>>    - *A* common/mpls.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-0> (296)
>>    - *A* common/mpls.h
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-1> (83)
>>    - *A* common/mpls.proto
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-2> (37)
>>    - *A* common/mpls.ui
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-3> (164)
>>    - *A* common/mplsconfig.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-4> (85)
>>    - *A* common/mplsconfig.h
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-5> (44)
>>    - *A* common/mplspdml.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-6> (42)
>>    - *A* common/mplspdml.h
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-7> (37)
>>    - *M* common/ostproto.pro
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-8> (3)
>>    - *M* common/ostprotogui.pro
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-9> (4)
>>    - *M* common/pdmlreader.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-10> (2)
>>    - *M* common/protocol.proto
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-11> (1)
>>    - *M* common/protocolmanager.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-12> (3)
>>    - *M* common/protocolwidgetfactory.cpp
>>    <https://github.com/pstavirs/ostinato/pull/162/files#diff-13> (4)
>>
>> Patch Links:
>>
>>    - https://github.com/pstavirs/ostinato/pull/162.patch
>>    - https://github.com/pstavirs/ostinato/pull/162.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pstavirs/ostinato/pull/162>.
>>
>
>
>
> --
> http://ostinato.org/
> @ostinato
>



-- 
http://ostinato.org/
@ostinato

**Comment by volchanetskiy** [comment]
> Is the choice of having default label value as 0 a considered/explicit reason?

I didn't set any value as default as I have no idea which value to use. Currently protobuf code sets it to 0.
> I think we should implement a label stack in the protocol instead of a single label.

It will require some changes in PDML import code as every MPLS label in a packet is described in a separate *proto* element.

**Comment by pstavirs** [comment]
* A label value of 0 indicates Explicit NULL label - which should be ok in
this case
* Yes, PDML import code will need change. See
PdmlVlanProtocol::preProtocolHandler() for an example of something similar
* The .proto file will also need to change to have a repeated embedded
message

Srivats

On Wed, Oct 21, 2015 at 12:50 PM, volchanetskiy <notifications@github.com>
wrote:

> Is the choice of having default label value as 0 a considered/explicit
> reason?
>
> I didn't set any value as default as I have no idea which value to use.
> Currently protobuf code sets it to 0.
>
> I think we should implement a label stack in the protocol instead of a
> single label.
>
> It will require some changes in PDML import code as every MPLS label in a
> packet is described in a separate *proto* element.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstavirs/ostinato/pull/162#issuecomment-150006476>.
>



-- 
http://ostinato.org/
@ostinato

**Comment by pstavirs** [comment]
Stale PR. Closing.

**Pull request closed without merging**
